build_packages: ignore grep -v exit status
If `grep -v` filters out all lines, then it will exit 1.  In this case,
we don't care, as we wanted it to filter everything out.  Ignore grep's
exit status in these commands.
$ echo foo | grep -v foo; echo $?
1

BUG=chromium:880982
TEST=precq passes

Change-Id: Ibfd34c3f8e7b06dacdd26bf1d694642ed6ba5dc5
Reviewed-on: https://chromium-review.googlesource.com/1208381
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Achuith Bhandarkar <achuith@chromium.org>
Reviewed-by: Gregory Meinke <gmeinke@chromium.org>

diff --git a/build_packages b/build_packages
--- a/build_packages
+++ b/build_packages
@@ -308,9 +308,10 @@ if [[ "${FLAGS_withrevdeps}" -eq "${FLAGS_TRUE}" ]]; then
     MOD_PKGS+=( $(\
     equery-${FLAGS_board} list -p -o --format='$category/$name' \
       "${BASE_INSTALL_PKGS[@]}" | sort -u ) )
-    # Remove Chrome as rebuilding it is expensive and almost never makes sense
+    # Remove Chrome as rebuilding it is expensive and almost never makes sense.
+    # Ignore grep exit status in case chromeos-chrome is the only package.
     MOD_PKGS=( $(printf '%s\n' "${MOD_PKGS[@]}" | \
-      grep -v 'chromeos-base/chromeos-chrome') )
+      grep -v 'chromeos-base/chromeos-chrome' || :) )
   fi
 
   FORCE_LOCAL_BUILD_PKGS+=( "${MOD_PKGS[@]}" )
@@ -325,9 +326,11 @@ if [[ "${FLAGS_withrevdeps}" -eq "${FLAGS_TRUE}" ]]; then
       RMOD_PKGS=( $(\
         equery-${FLAGS_board} -q list -p -o --format='$category/$name' \
         "${REV_DEPS[@]}" | sort -u ) )
-      # Remove Chrome as rebuilding it is expensive and almost never makes sense
+      # Remove Chrome as rebuilding it is expensive and almost never makes
+      # sense.  Ignore grep exit status in case chromeos-chrome is the only
+      # package.
       RMOD_PKGS=( $(printf '%s\n' "${RMOD_PKGS[@]}" | \
-        grep -v 'chromeos-base/chromeos-chrome') )
+        grep -v 'chromeos-base/chromeos-chrome' || :) )
       info "final reverse dependencies that will be rebuilt: ${RMOD_PKGS[*]}"
       FORCE_LOCAL_BUILD_PKGS+=( "${RMOD_PKGS[@]}" )
     fi
