Fail when the chroot version is too new.
This enables us to know when to run cros_sdk --replace in cbuildbot.

BUG=none
TEST=Verify upgrades still work.
TEST=Run the script with a too-new chroot version, verify it fails now.

Change-Id: Ie81bc7d86d56c033c1298c3bb7ed91b64fff9464
Reviewed-on: https://gerrit.chromium.org/gerrit/46978
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Tested-by: David James <davidjames@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>

diff --git a/run_chroot_version_hooks b/run_chroot_version_hooks
--- a/run_chroot_version_hooks
+++ b/run_chroot_version_hooks
@@ -149,6 +149,10 @@ if [ "${LATEST_VERSION}" -gt "${CHROOT_VERSION}" ]; then
     update_version "${n}"
   done
   popd 1> /dev/null
+elif [ "${LATEST_VERSION}" -lt "${CHROOT_VERSION}" ]; then
+  error "Fatal: Missing upgrade hook for ${CHROOT_VERSION}"
+  error "Chroot version is too new. Consider running cros_sdk --replace"
+  exit 1
 fi
 
 command_completed
