setup_board: Reorder the configuration generation.
This simplifies the scripts and allows us to rely on standard fields.

BUG=brillo:662
TEST=trybot runs on daisy, link, gizmo, lumpy-incremental,
  chromiumos-sdk.

CQ-DEPEND=CL:263593

Change-Id: Icdec26b8dc42be1252b02ba005fde96e7d1c29e8
Reviewed-on: https://chromium-review.googlesource.com/262922
Reviewed-by: David James <davidjames@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Bertrand Simonnet <bsimonnet@chromium.org>
Tested-by: Bertrand Simonnet <bsimonnet@chromium.org>

diff --git a/setup_board b/setup_board
--- a/setup_board
+++ b/setup_board
@@ -126,6 +126,7 @@ print_board_binhost_config() {
   local chrome_binhost_suffix="LATEST_RELEASE_CHROME_BINHOST.conf"
   local partner_overlay="$SRC_ROOT/private-overlays/chromeos-partner-overlay"
   local internal_binhost_dir="$partner_overlay/chromeos/binhost/target"
+  local arch="$(get_sysroot_config "${BOARD_ROOT}" "ARCH")"
   # i_arch_map / e_arch_map: maps architectures to internal / external boards.
   # i_kernel_map / e_kernel_map: maps kernels to internal / external boards.
   declare -A i_arch_map e_arch_map e_kernel_map i_kernel_map \
@@ -160,8 +161,8 @@ print_board_binhost_config() {
   # be shared everywhere. The same isn't true for internal "generic" boards.
   # For that reason, the internal "generic" boards can only be used for the
   # Chrome binhost.
-  local e_generic="${e_kernel_map[${kernel:-none}]:-${e_arch_map[${ARCH}]:-}}"
-  local i_generic="${i_kernel_map[${kernel:-none}]:-${i_arch_map[${ARCH}]:-}}"
+  local e_generic="${e_kernel_map[${kernel:-none}]:-${e_arch_map[${arch}]:-}}"
+  local i_generic="${i_kernel_map[${kernel:-none}]:-${i_arch_map[${arch}]:-}}"
   local e_chrome="" i_chrome=""
   if has ozone $(portageq-${BOARD_VARIANT} envvar USE); then
     # If ozone use flag is present, the grab Chrome prebuilts from a builder
@@ -177,8 +178,8 @@ print_board_binhost_config() {
     if has ozone_platform_default_dri $(portageq-${BOARD_VARIANT} envvar USE); then
       i_chrome_arch_map['arm']='rush_ryu'
     fi
-    e_chrome="${e_chrome_arch_map[${ARCH}]:-}"
-    i_chrome="${i_chrome_arch_map[${ARCH}]:-}"
+    e_chrome="${e_chrome_arch_map[${arch}]:-}"
+    i_chrome="${i_chrome_arch_map[${arch}]:-}"
   fi
   if [[ "${BOARD}" == "veyron" ]]; then
     i_chrome="veyron_pinky"
@@ -287,19 +288,6 @@ if [ "${FLAGS_skip_chroot_upgrade}" -eq "${FLAGS_FALSE}" ] ; then
   "${SRC_ROOT}/scripts"/update_chroot ${UPDATE_ARGS}
 fi
 
-#
-# Fetch the toolchain from the board overlay.
-#
-all_toolchains=( $(get_all_board_toolchains "${FLAGS_brick:-${BOARD}}") )
-: ${FLAGS_toolchain:=${all_toolchains[0]}}
-
-if [ -z "${FLAGS_toolchain}" ]; then
-  error "No toolchain specified in board overlay or on command line."
-  exit 1
-fi
-
-ARCH=$(get_board_arch "${FLAGS_brick:-${BOARD}}") || exit 1
-
 case "$BOARD" in
   *-host)
     if [[ $FLAGS_usepkg -eq $FLAGS_TRUE ]]; then
@@ -322,6 +310,7 @@ BOARD_PROFILE="${BOARD_ETC}/portage/profile"
 
 eval $(portageq envvar -v CHOST PKGDIR)
 
+SYSROOT_EXISTS=false
 if [ -d "${BOARD_ROOT}" ]; then
   if [[ ${FLAGS_force} -eq ${FLAGS_TRUE} ]]; then
     echo "--force set.  Re-creating ${BOARD_ROOT}..."
@@ -330,89 +319,16 @@ if [ -d "${BOARD_ROOT}" ]; then
     sudo mv "${BOARD_ROOT}" "${TEMP_DIR}"
     sudo rm -rf --one-file-system "${TEMP_DIR}" &
   else
-    if ! ${HOST_BOARD}; then
-      { print_board_make_conf; print_board_binhost_config; } | \
-        sudo_clobber $BOARD_ETC/make.conf.board
-    fi
-    if [[ ${FLAGS_regen_configs} -eq ${FLAGS_FALSE} ]]; then
-      if [[ ${FLAGS_quiet} -eq ${FLAGS_FALSE} ]]; then
-        warn "Board output directory '$BOARD_ROOT' already exists."
-        warn "Not setting up board root. "
-        warn "Use --force to clobber the board root and start again."
-      fi
-      if [[ ${FLAGS_skip_board_pkg_init} -eq ${FLAGS_FALSE} ]]; then
-        # Update the users libc in their board if needed.
-        install_toolchain
-      fi
-      exit 0
-    fi
+    # The sysroot exists. Take note so that we can exit early once the
+    # configuration has been updated.
+    SYSROOT_EXISTS=true
   fi
 else
   # Regenerating configs w/out a board root doesn't make sense.
   FLAGS_regen_configs=${FLAGS_FALSE}
 fi
 
-cmds=(
-  "mkdir -p '${BOARD_ROOT}' '${BOARD_ETC}' '${BOARD_PROFILE}' /usr/local/bin"
-)
-
-# Setup the make.confs. We use the following:
-#    make.conf             <- Overall target make.conf [arm, x86, etc. version]
-#    make.conf.board_setup <- Declares CHOST, ROOT, etc.
-#    make.conf.board       <- Optional board-supplied make.conf
-if ${HOST_BOARD}; then
-  cmds+=(
-    "ln -sf '${CHROMIUMOS_CONFIG}/make.conf.${BOARD}' \
-      '${BOARD_ETC}/make.conf'"
-    "cp -f '/etc/make.conf.host_setup' '${BOARD_ETC}/'"
-
-    # Setting up symlinks for bootstrapping multilib.
-    # See http://crosbug.com/14498
-    "mkdir -p '${BOARD_ROOT}'{/usr,}/lib64"
-    "ln -sfT lib64 '${BOARD_ROOT}/lib'"
-    "ln -sfT lib64 '${BOARD_ROOT}/usr/lib'"
-
-    # Copying some files for bootstrapping empty chroot.
-    # See http://crosbug.com/14499
-    "mkdir -p '${BOARD_ETC}'/{init.d,xml}"
-    "cp /etc/xml/catalog '${BOARD_ETC}'/xml/"
-    "cp /etc/init.d/functions.sh '${BOARD_ETC}'/init.d/"
-  )
-fi
-sudo_multi "${cmds[@]}"
-
-SAVED_VERSION=
-if [[ ${FLAGS_regen_configs} -eq ${FLAGS_TRUE} ]]; then
-  SAVED_VERSION=$(grep -s ^LIBC_VERSION= ${BOARD_SETUP} || true)
-fi
-
-if [[ -n "${FLAGS_brick}" ]]; then
-  cros_sysroot_utils generate-config --sysroot="${BOARD_ROOT}" \
-    --brick="${FLAGS_brick}" --out-file="${BOARD_SETUP}"
-else
-  cros_sysroot_utils generate-config --sysroot="${BOARD_ROOT}" \
-    --board="${FLAGS_board}" --out-file="${BOARD_SETUP}"
-fi
-printf "\n%s\n" "${SAVED_VERSION}" | sudo_append "${BOARD_SETUP}"
-
-if ! ${HOST_BOARD}; then
-  for a in ${ARCH} generic; do
-    conf="${CHROMIUMOS_CONFIG}/make.conf.${a}-target"
-    if [[ -e ${conf} ]]; then
-      sudo ln -sf "${conf}" "${BOARD_ETC}/make.conf"
-      break
-    fi
-  done
-  print_board_make_conf | sudo_clobber $BOARD_ETC/make.conf.board
-
-  # We install the toolchain related bits after the BOARD_ROOT, BOARD_PROFILE
-  # and BOARD_ETC directories have been created.
-  if [[ ${FLAGS_regen_configs} -eq ${FLAGS_FALSE}  && \
-        ${FLAGS_skip_board_pkg_init} -eq ${FLAGS_FALSE} ]]; then
-    install_toolchain
-  fi
-fi
-# Setup the profile.
+# Setup the user specific profile.
 if [[ ! -s /etc/make.conf.user ]]; then
   sudo_clobber /etc/make.conf.user <<\EOF
 # This file is useful for doing global (chroot and all board) changes.
@@ -428,7 +344,14 @@ if [[ ! -s /etc/make.conf.user ]]; then
 # This also is a good place to setup ACCEPT_LICENSE.
 EOF
 fi
+
+# Setup the make.confs. We use the following:
+#    make.conf             <- Overall target make.conf [arm, x86, etc. version]
+#    make.conf.board_setup <- Declares CHOST, ROOT, etc.
+#    make.conf.board       <- Optional board-supplied make.conf.
+#    make.conf.user        <- User specified parameters.
 cmds=(
+  "mkdir -p '${BOARD_ROOT}' '${BOARD_ETC}' '${BOARD_PROFILE}' /usr/local/bin"
   "ln -sf /etc/make.conf.user '${BOARD_ROOT}/etc/make.conf.user'"
   "mkdir -p '${BOARD_ROOT}/etc/portage/hooks'"
 )
@@ -437,25 +360,53 @@ for d in "${SCRIPTS_DIR}"/hooks/*; do
 done
 sudo_multi "${cmds[@]}"
 
+# Generating the standard configuration file (make.conf.board_setup) for the
+# sysroot.
+SAVED_VERSION="$(get_sysroot_config "${BOARD_SETUP}" "LIBC_VERSION")"
+if [[ -n "${FLAGS_brick}" ]]; then
+  cros_sysroot_utils generate-config --sysroot="${BOARD_ROOT}" \
+    --brick="${FLAGS_brick}" --out-file="${BOARD_SETUP}"
+else
+  cros_sysroot_utils generate-config --sysroot="${BOARD_ROOT}" \
+    --board="${FLAGS_board}" --out-file="${BOARD_SETUP}"
+fi
+printf "\n%s\n" "${SAVED_VERSION}" | sudo_append "${BOARD_SETUP}"
+
+# Generate wrappers for portage helpers (equery, portageq, emerge, etc...).
+# Those are used to generate make.conf.board.
+cros_sysroot_utils create-wrappers --sysroot="${BOARD_ROOT}" \
+  --friendlyname="${BOARD_VARIANT}"
+
 # Select the profile to build based on the board and profile passed to
 # setup_board.  The developer can later change profiles by running
 # cros_choose_profile manually.
-if ! cros_choose_profile \
-       --board "${FLAGS_board}" \
-       --board_overlay "${FLAGS_board_overlay}" \
-       --variant "${FLAGS_variant}" \
-       --brick "${FLAGS_brick}" \
-       --profile "${FLAGS_profile}" \
-       --board_root "${BOARD_ROOT}"; then
-  error "Selecting profile failed, removing incomplete board directory!"
+if ! cros_choose_profile --profile "${FLAGS_profile}" \
+      --board_root "${BOARD_ROOT}"; then
   sudo rm -rf --one-file-system "${BOARD_ROOT}"
-  exit 1
+  die "Selecting profile failed, removing incomplete board directory!"
 fi
 
-cros_sysroot_utils create-wrappers --sysroot="${BOARD_ROOT}" \
-  --toolchain="${FLAGS_toolchain}" --friendlyname="${BOARD_VARIANT}"
-
 if ${HOST_BOARD}; then
+  cmds=(
+    "ln -sf '${CHROMIUMOS_CONFIG}/make.conf.${BOARD}' \
+      '${BOARD_ETC}/make.conf'"
+    "cp -f '/etc/make.conf.host_setup' '${BOARD_ETC}/'"
+
+    # Setting up symlinks for bootstrapping multilib.
+    # See http://crosbug.com/14498
+    "mkdir -p '${BOARD_ROOT}'{/usr,}/lib64"
+    "ln -sfT lib64 '${BOARD_ROOT}/lib'"
+    "rm -r '${BOARD_ROOT}/usr/lib'"
+    "ln -sfT lib64 '${BOARD_ROOT}/usr/lib'"
+
+    # Copying some files for bootstrapping empty chroot.
+    # See http://crosbug.com/14499
+    "mkdir -p '${BOARD_ETC}'/{init.d,xml}"
+    "cp /etc/xml/catalog '${BOARD_ETC}'/xml/"
+    "cp /etc/init.d/functions.sh '${BOARD_ETC}'/init.d/"
+  )
+  sudo_multi "${cmds[@]}"
+
   EMERGE_CMD="${GCLIENT_ROOT}/chromite/bin/parallel_emerge"
   PACKAGES="system virtual/target-sdk world"
 
@@ -477,23 +428,49 @@ if ${HOST_BOARD}; then
   sudo find $BOARD_ROOT -type f -name '*.la' | xargs sudo \
       sed -i -e "s|$BOARD_ROOT/|/|g"
 else
-  # Now that the portageq-* wrappers have been created, we can add the binhost
-  # config to make.conf.board.
+  for a in $(get_sysroot_config "${BOARD_ROOT}" "ARCH") generic; do
+    conf="${CHROMIUMOS_CONFIG}/make.conf.${a}-target"
+    if [[ -e ${conf} ]]; then
+      sudo ln -sf "${conf}" "${BOARD_ETC}/make.conf"
+      break
+    fi
+  done
+  print_board_make_conf | sudo_clobber $BOARD_ETC/make.conf.board
+
+  # We need to create make.conf.board in two steps as we need make.conf.board to
+  # exist before we can generate the binhost list.
   print_board_binhost_config | sudo_append $BOARD_ETC/make.conf.board
 
-  if [[ ${FLAGS_regen_configs} -eq ${FLAGS_FALSE}  && \
-        ${FLAGS_skip_board_pkg_init} -eq ${FLAGS_FALSE} ]]; then
-    # Emerge the kernel headers into the board build root.  Use rdeps to
-    # avoid pulling any spurious DEPEND things in that we don't care about.
-    BASE_EMERGE_FLAGS="--select --quiet --root-deps=rdeps"
-    if [[ "${FLAGS_usepkg}" -eq "${FLAGS_TRUE}" ||
-          "${FLAGS_reuse_pkgs_from_local_boards}" -eq "${FLAGS_TRUE}" ]]; then
-      BASE_EMERGE_FLAGS+=" --getbinpkg --usepkg"
+  # We install the toolchain related bits after the BOARD_ROOT, BOARD_PROFILE
+  # and BOARD_ETC directories have been created.
+  if [[ ${FLAGS_regen_configs} -eq ${FLAGS_FALSE} ]]; then
+    if [[ ${FLAGS_skip_board_pkg_init} -eq ${FLAGS_FALSE} ]]; then
+      install_toolchain
     fi
 
-    sudo -E "emerge-${BOARD_VARIANT}" ${BASE_EMERGE_FLAGS} \
-      sys-kernel/linux-headers sys-libs/gcc-libs
-    unset BASE_EMERGE_FLAGS
+    # If the sysroot already existed and we are not regenerating configuration,
+    # exit early.
+    if ${SYSROOT_EXISTS}; then
+      if [[ ${FLAGS_quiet} -eq ${FLAGS_FALSE} ]]; then
+        warn "Board output directory '$BOARD_ROOT' already exists."
+        warn "Exiting early."
+        warn "Use --force to clobber the board root and start again."
+      fi
+      exit 0
+    fi
+    if [[ ${FLAGS_skip_board_pkg_init} -eq ${FLAGS_FALSE} ]]; then
+      # Emerge the kernel headers into the board build root.  Use rdeps to
+      # avoid pulling any spurious DEPEND things in that we don't care about.
+      BASE_EMERGE_FLAGS="--select --quiet --root-deps=rdeps"
+      if [[ "${FLAGS_usepkg}" -eq "${FLAGS_TRUE}" ||
+            "${FLAGS_reuse_pkgs_from_local_boards}" -eq "${FLAGS_TRUE}" ]]; then
+        BASE_EMERGE_FLAGS+=" --getbinpkg --usepkg"
+      fi
+
+      sudo -E "emerge-${BOARD_VARIANT}" ${BASE_EMERGE_FLAGS} \
+        sys-kernel/linux-headers sys-libs/gcc-libs
+      unset BASE_EMERGE_FLAGS
+    fi
   fi
 fi
 
